[workspace]
members = [
    "puffin",
    "puffin_egui",
    "puffin_http",
    "puffin-imgui",
    "puffin_viewer",
]

[patch.crates-io]
imgui = { git = "https://github.com/EmbarkStudios/imgui-rs", rev = "97d6242" }
imgui-winit-support = { git = "https://github.com/EmbarkStudios/imgui-rs", rev = "97d6242" }
