
# cargo-vet config file

[cargo-vet]
version = "0.7"

[imports.embark]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.fermyon]
url = "https://raw.githubusercontent.com/fermyon/spin/main/supply-chain/audits.toml"

[imports.firefox]
url = "https://hg.mozilla.org/mozilla-central/raw-file/tip/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.google.criteria-map]
safe-to-run = "safe-to-deploy"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.wasmtime]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.errno-dragonfly]
criteria = []
notes = "Not used, unsupported target"

[policy.orbclient]
criteria = []
notes = "Not used, Redox OS-only"

[policy.puffin]
audit-as-crates-io = false

[policy.puffin-imgui]
audit-as-crates-io = false

[policy.puffin_egui]
audit-as-crates-io = false

[policy.puffin_http]
audit-as-crates-io = false

[policy.puffin_viewer]
audit-as-crates-io = false

[policy.redox_syscall]
criteria = []
notes = "Not used, Redox OS-only"

[policy.redox_users]
criteria = []
notes = "Not used, Redox OS-only"

[policy.wasi]
criteria = []
notes = "Not used, unsupported target"

[[exemptions.ab_glyph]]
version = "0.2.20"
criteria = "safe-to-deploy"

[[exemptions.ab_glyph_rasterizer]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.accesskit]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.addr2line]]
version = "0.17.0"
criteria = "safe-to-run"

[[exemptions.adler]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.ahash]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.android-activity]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.android-properties]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.arboard]]
version = "3.2.0"
criteria = "safe-to-deploy"

[[exemptions.argh]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.argh_derive]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.argh_shared]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.arrayvec]]
version = "0.5.2"
criteria = "safe-to-run"

[[exemptions.atk-sys]]
version = "0.15.1"
criteria = "safe-to-deploy"

[[exemptions.bincode]]
version = "1.3.3"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.block]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.block-sys]]
version = "0.1.0-beta.1"
criteria = "safe-to-deploy"

[[exemptions.block2]]
version = "0.2.0-alpha.6"
criteria = "safe-to-deploy"

[[exemptions.bytemuck_derive]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.cairo-sys-rs]]
version = "0.15.1"
criteria = "safe-to-deploy"

[[exemptions.calloop]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.cast]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.cesu8]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.cgl]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.chlorine]]
version = "1.0.10"
criteria = "safe-to-deploy"

[[exemptions.clipboard-win]]
version = "4.4.2"
criteria = "safe-to-deploy"

[[exemptions.colored]]
version = "2.0.0"
criteria = "safe-to-run"

[[exemptions.combine]]
version = "4.6.4"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.criterion]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.crossbeam-channel]]
version = "0.5.4"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-deque]]
version = "0.8.1"
criteria = "safe-to-run"

[[exemptions.crossbeam-epoch]]
version = "0.9.8"
criteria = "safe-to-run"

[[exemptions.crossbeam-utils]]
version = "0.8.8"
criteria = "safe-to-deploy"

[[exemptions.crossfont]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.darling]]
version = "0.13.4"
criteria = "safe-to-run"

[[exemptions.darling_core]]
version = "0.13.4"
criteria = "safe-to-run"

[[exemptions.darling_macro]]
version = "0.13.4"
criteria = "safe-to-run"

[[exemptions.directories-next]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.dirs]]
version = "4.0.0"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys]]
version = "0.3.7"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys-next]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.dispatch]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.dlib]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.downcast-rs]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.error-code]]
version = "2.3.1"
criteria = "safe-to-deploy"

[[exemptions.expat-sys]]
version = "2.1.6"
criteria = "safe-to-run"

[[exemptions.fdeflate]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.foreign-types]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.foreign-types-macros]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.foreign-types-shared]]
version = "0.3.1"
criteria = "safe-to-run"

[[exemptions.form_urlencoded]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.freetype-rs]]
version = "0.26.0"
criteria = "safe-to-run"

[[exemptions.freetype-sys]]
version = "0.13.1"
criteria = "safe-to-run"

[[exemptions.gdk-pixbuf-sys]]
version = "0.15.10"
criteria = "safe-to-deploy"

[[exemptions.gdk-sys]]
version = "0.15.1"
criteria = "safe-to-deploy"

[[exemptions.gethostname]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.26.1"
criteria = "safe-to-run"

[[exemptions.gio-sys]]
version = "0.15.10"
criteria = "safe-to-deploy"

[[exemptions.gl_generator]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.glib-sys]]
version = "0.15.10"
criteria = "safe-to-deploy"

[[exemptions.glium]]
version = "0.32.1"
criteria = "safe-to-run"

[[exemptions.glow]]
version = "0.12.0"
criteria = "safe-to-deploy"

[[exemptions.glutin]]
version = "0.29.1"
criteria = "safe-to-run"

[[exemptions.glutin]]
version = "0.30.3"
criteria = "safe-to-deploy"

[[exemptions.glutin-winit]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.glutin_egl_sys]]
version = "0.1.6"
criteria = "safe-to-run"

[[exemptions.glutin_egl_sys]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.glutin_gles2_sys]]
version = "0.1.5"
criteria = "safe-to-run"

[[exemptions.glutin_glx_sys]]
version = "0.1.8"
criteria = "safe-to-run"

[[exemptions.glutin_glx_sys]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.glutin_wgl_sys]]
version = "0.1.5"
criteria = "safe-to-run"

[[exemptions.glutin_wgl_sys]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.gobject-sys]]
version = "0.15.10"
criteria = "safe-to-deploy"

[[exemptions.gtk-sys]]
version = "0.15.3"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.1.19"
criteria = "safe-to-run"

[[exemptions.hermit-abi]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.humantime]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.image]]
version = "0.24.6"
criteria = "safe-to-deploy"

[[exemptions.imgui]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.imgui-glium-renderer]]
version = "0.10.0"
criteria = "safe-to-run"

[[exemptions.imgui-sys]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.imgui-winit-support]]
version = "0.10.0"
criteria = "safe-to-run"

[[exemptions.instant]]
version = "0.1.12"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.10.3"
criteria = "safe-to-run"

[[exemptions.jni]]
version = "0.20.0"
criteria = "safe-to-deploy"

[[exemptions.jni-sys]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.khronos_api]]
version = "3.1.0"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.144"
criteria = "safe-to-deploy"

[[exemptions.libloading]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.libmimalloc-sys]]
version = "0.1.25"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.7"
criteria = "safe-to-deploy"

[[exemptions.lz4_flex]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.memmap2]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.memmap2]]
version = "0.5.8"
criteria = "safe-to-deploy"

[[exemptions.memoffset]]
version = "0.6.5"
criteria = "safe-to-deploy"

[[exemptions.mimalloc]]
version = "0.1.29"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.5.1"
criteria = "safe-to-run"

[[exemptions.mint]]
version = "0.5.9"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.ndk]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.ndk-glue]]
version = "0.7.0"
criteria = "safe-to-run"

[[exemptions.ndk-macro]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.ndk-sys]]
version = "0.4.1+23.1.7779620"
criteria = "safe-to-deploy"

[[exemptions.nix]]
version = "0.22.3"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "7.1.1"
criteria = "safe-to-deploy"

[[exemptions.num_enum]]
version = "0.5.7"
criteria = "safe-to-deploy"

[[exemptions.num_enum_derive]]
version = "0.5.7"
criteria = "safe-to-deploy"

[[exemptions.objc]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.objc-foundation]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.objc-sys]]
version = "0.2.0-beta.2"
criteria = "safe-to-deploy"

[[exemptions.objc2]]
version = "0.3.0-beta.3"
criteria = "safe-to-deploy"

[[exemptions.objc2-encode]]
version = "2.0.0-pre.2"
criteria = "safe-to-deploy"

[[exemptions.objc_id]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.28.4"
criteria = "safe-to-run"

[[exemptions.once_cell]]
version = "1.13.1"
criteria = "safe-to-deploy"

[[exemptions.osmesa-sys]]
version = "0.1.2"
criteria = "safe-to-run"

[[exemptions.owned_ttf_parser]]
version = "0.18.1"
criteria = "safe-to-deploy"

[[exemptions.pango-sys]]
version = "0.15.10"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.12.0"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.3"
criteria = "safe-to-deploy"

[[exemptions.percent-encoding]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.plotters]]
version = "0.3.1"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.2"
criteria = "safe-to-run"

[[exemptions.plotters-svg]]
version = "0.3.1"
criteria = "safe-to-run"

[[exemptions.proc-macro-crate]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.raw-window-handle]]
version = "0.4.3"
criteria = "safe-to-run"

[[exemptions.rfd]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.ron]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.ruzstd]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.safe_arch]]
version = "0.5.2"
criteria = "safe-to-run"

[[exemptions.sctk-adwaita]]
version = "0.4.2"
criteria = "safe-to-run"

[[exemptions.sctk-adwaita]]
version = "0.5.3"
criteria = "safe-to-deploy"

[[exemptions.servo-fontconfig]]
version = "0.5.1"
criteria = "safe-to-run"

[[exemptions.servo-fontconfig-sys]]
version = "5.1.0"
criteria = "safe-to-run"

[[exemptions.shared_library]]
version = "0.1.9"
criteria = "safe-to-run"

[[exemptions.simd-adler32]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.simple_logger]]
version = "2.1.0"
criteria = "safe-to-run"

[[exemptions.slotmap]]
version = "1.0.6"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.smithay-client-toolkit]]
version = "0.15.4"
criteria = "safe-to-deploy"

[[exemptions.smithay-client-toolkit]]
version = "0.16.0"
criteria = "safe-to-deploy"

[[exemptions.smithay-clipboard]]
version = "0.6.5"
criteria = "safe-to-deploy"

[[exemptions.str-buf]]
version = "1.0.5"
criteria = "safe-to-deploy"

[[exemptions.strict-num]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.10.0"
criteria = "safe-to-run"

[[exemptions.system-deps]]
version = "6.0.2"
criteria = "safe-to-deploy"

[[exemptions.takeable-option]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.thiserror-core]]
version = "1.0.38"
criteria = "safe-to-deploy"

[[exemptions.thiserror-core-impl]]
version = "1.0.38"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.17"
criteria = "safe-to-deploy"

[[exemptions.time-core]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.time-macros]]
version = "0.2.6"
criteria = "safe-to-deploy"

[[exemptions.tiny-skia]]
version = "0.7.0"
criteria = "safe-to-run"

[[exemptions.tiny-skia]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.tiny-skia-path]]
version = "0.7.0"
criteria = "safe-to-run"

[[exemptions.tiny-skia-path]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.tinytemplate]]
version = "1.2.1"
criteria = "safe-to-run"

[[exemptions.toml]]
version = "0.5.9"
criteria = "safe-to-deploy"

[[exemptions.ttf-parser]]
version = "0.18.1"
criteria = "safe-to-deploy"

[[exemptions.twox-hash]]
version = "1.6.3"
criteria = "safe-to-deploy"

[[exemptions.url]]
version = "2.2.2"
criteria = "safe-to-deploy"

[[exemptions.vec1]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.version-compare]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.86"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.86"
criteria = "safe-to-deploy"

[[exemptions.wayland-client]]
version = "0.29.5"
criteria = "safe-to-deploy"

[[exemptions.wayland-commons]]
version = "0.29.5"
criteria = "safe-to-deploy"

[[exemptions.wayland-cursor]]
version = "0.29.4"
criteria = "safe-to-deploy"

[[exemptions.wayland-egl]]
version = "0.29.4"
criteria = "safe-to-run"

[[exemptions.wayland-protocols]]
version = "0.29.5"
criteria = "safe-to-deploy"

[[exemptions.wayland-scanner]]
version = "0.29.5"
criteria = "safe-to-deploy"

[[exemptions.wayland-sys]]
version = "0.29.5"
criteria = "safe-to-deploy"

[[exemptions.wayland-sys]]
version = "0.30.1"
criteria = "safe-to-deploy"

[[exemptions.webbrowser]]
version = "0.8.7"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-wsapoll]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows]]
version = "0.37.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.36.1"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.36.1"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.37.0"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.36.1"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.37.0"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.36.1"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.37.0"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.36.1"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.37.0"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.36.1"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.37.0"
criteria = "safe-to-deploy"

[[exemptions.winit]]
version = "0.27.2"
criteria = "safe-to-run"

[[exemptions.winit]]
version = "0.28.1"
criteria = "safe-to-deploy"

[[exemptions.wio]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.x11-dl]]
version = "2.20.1"
criteria = "safe-to-deploy"

[[exemptions.x11rb]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.x11rb-protocol]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.xcursor]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.xml-rs]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.zstd]]
version = "0.12.3+zstd.1.5.2"
criteria = "safe-to-deploy"

[[exemptions.zstd-safe]]
version = "6.0.5+zstd.1.5.4"
criteria = "safe-to-deploy"

[[exemptions.zstd-sys]]
version = "2.0.8+zstd.1.5.5"
criteria = "safe-to-deploy"
