
# cargo-vet config file

[cargo-vet]
version = "0.8"

[imports.embark]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.fermyon]
url = "https://raw.githubusercontent.com/fermyon/spin/main/supply-chain/audits.toml"

[imports.firefox]
url = "https://hg.mozilla.org/mozilla-central/raw-file/tip/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.google.criteria-map]
safe-to-run = "safe-to-deploy"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.wasmtime]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.errno-dragonfly]
criteria = []
notes = "Not used, unsupported target"

[policy.orbclient]
criteria = []
notes = "Not used, Redox OS-only"

[policy.puffin]
audit-as-crates-io = false

[policy.puffin_egui]
audit-as-crates-io = false

[policy.puffin_http]
audit-as-crates-io = false

[policy.puffin_viewer]
audit-as-crates-io = false

[policy.redox_syscall]
criteria = []
notes = "Not used, Redox OS-only"

[policy.redox_users]
criteria = []
notes = "Not used, Redox OS-only"

[policy.wasi]
criteria = []
notes = "Not used, unsupported target"

[[exemptions.ab_glyph_rasterizer]]
version = "0.1.8"
criteria = "safe-to-deploy"

[[exemptions.accesskit]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.ahash]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.android-properties]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.arboard]]
version = "3.2.0"
criteria = "safe-to-deploy"

[[exemptions.atk-sys]]
version = "0.15.1"
criteria = "safe-to-deploy"

[[exemptions.atomic_refcell]]
version = "0.1.10"
criteria = "safe-to-deploy"

[[exemptions.bincode]]
version = "1.3.3"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.block]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.block-sys]]
version = "0.1.0-beta.1"
criteria = "safe-to-deploy"

[[exemptions.block2]]
version = "0.2.0-alpha.6"
criteria = "safe-to-deploy"

[[exemptions.bytemuck_derive]]
version = "1.4.1"
criteria = "safe-to-deploy"

[[exemptions.cairo-sys-rs]]
version = "0.15.1"
criteria = "safe-to-deploy"

[[exemptions.calloop]]
version = "0.10.6"
criteria = "safe-to-deploy"

[[exemptions.cast]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.cesu8]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.cgl]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.ciborium]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.ciborium-io]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.ciborium-ll]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.clipboard-win]]
version = "4.5.0"
criteria = "safe-to-deploy"

[[exemptions.colored]]
version = "2.0.0"
criteria = "safe-to-run"

[[exemptions.combine]]
version = "4.6.6"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.criterion]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.directories-next]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys-next]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.dispatch]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.dlib]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.downcast-rs]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.error-code]]
version = "2.3.1"
criteria = "safe-to-deploy"

[[exemptions.gdk-pixbuf-sys]]
version = "0.15.10"
criteria = "safe-to-deploy"

[[exemptions.gdk-sys]]
version = "0.15.1"
criteria = "safe-to-deploy"

[[exemptions.gethostname]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.gio-sys]]
version = "0.15.10"
criteria = "safe-to-deploy"

[[exemptions.gl_generator]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.glib-sys]]
version = "0.15.10"
criteria = "safe-to-deploy"

[[exemptions.glow]]
version = "0.12.2"
criteria = "safe-to-deploy"

[[exemptions.glutin]]
version = "0.30.8"
criteria = "safe-to-deploy"

[[exemptions.glutin-winit]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.glutin_egl_sys]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.glutin_glx_sys]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.glutin_wgl_sys]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.gobject-sys]]
version = "0.15.10"
criteria = "safe-to-deploy"

[[exemptions.gtk-sys]]
version = "0.15.3"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.1.19"
criteria = "safe-to-run"

[[exemptions.hermit-abi]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.home]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.humantime]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.image]]
version = "0.24.6"
criteria = "safe-to-deploy"

[[exemptions.instant]]
version = "0.1.12"
criteria = "safe-to-deploy"

[[exemptions.jni-sys]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.khronos_api]]
version = "3.1.0"
criteria = "safe-to-deploy"

[[exemptions.libloading]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.libloading]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.libmimalloc-sys]]
version = "0.1.33"
criteria = "safe-to-deploy"

[[exemptions.lz4_flex]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.memmap2]]
version = "0.5.10"
criteria = "safe-to-deploy"

[[exemptions.memoffset]]
version = "0.6.5"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.ndk]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.ndk-sys]]
version = "0.4.1+23.1.7779620"
criteria = "safe-to-deploy"

[[exemptions.nix]]
version = "0.15.0"
criteria = "safe-to-deploy"

[[exemptions.nix]]
version = "0.24.3"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "7.1.1"
criteria = "safe-to-deploy"

[[exemptions.objc]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.objc-foundation]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.objc-sys]]
version = "0.2.0-beta.2"
criteria = "safe-to-deploy"

[[exemptions.objc2]]
version = "0.3.0-beta.3.patch-leaks.3"
criteria = "safe-to-deploy"

[[exemptions.objc2-encode]]
version = "2.0.0-pre.2"
criteria = "safe-to-deploy"

[[exemptions.objc_id]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.owned_ttf_parser]]
version = "0.19.0"
criteria = "safe-to-deploy"

[[exemptions.pango-sys]]
version = "0.15.10"
criteria = "safe-to-deploy"

[[exemptions.pkg-config]]
version = "0.3.27"
criteria = "safe-to-deploy"

[[exemptions.plotters]]
version = "0.3.4"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.4"
criteria = "safe-to-run"

[[exemptions.proc-macro-crate]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.raw-window-handle]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.7.2"
criteria = "safe-to-deploy"

[[exemptions.rfd]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.ron]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.ruzstd]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.scoped-tls]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.sctk-adwaita]]
version = "0.5.4"
criteria = "safe-to-deploy"

[[exemptions.simd-adler32]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.simple_logger]]
version = "2.3.0"
criteria = "safe-to-run"

[[exemptions.slotmap]]
version = "1.0.6"
criteria = "safe-to-deploy"

[[exemptions.smithay-client-toolkit]]
version = "0.16.0"
criteria = "safe-to-deploy"

[[exemptions.smithay-clipboard]]
version = "0.6.6"
criteria = "safe-to-deploy"

[[exemptions.str-buf]]
version = "1.0.6"
criteria = "safe-to-deploy"

[[exemptions.strict-num]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.system-deps]]
version = "6.1.0"
criteria = "safe-to-deploy"

[[exemptions.target-lexicon]]
version = "0.12.7"
criteria = "safe-to-deploy"

[[exemptions.thiserror-core]]
version = "1.0.38"
criteria = "safe-to-deploy"

[[exemptions.thiserror-core-impl]]
version = "1.0.38"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.22"
criteria = "safe-to-deploy"

[[exemptions.time-macros]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.tiny-skia]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.tiny-skia-path]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.tinytemplate]]
version = "1.2.1"
criteria = "safe-to-run"

[[exemptions.toml_edit]]
version = "0.19.10"
criteria = "safe-to-deploy"

[[exemptions.twox-hash]]
version = "1.6.3"
criteria = "safe-to-deploy"

[[exemptions.url]]
version = "2.4.0"
criteria = "safe-to-deploy"

[[exemptions.wayland-client]]
version = "0.29.5"
criteria = "safe-to-deploy"

[[exemptions.wayland-commons]]
version = "0.29.5"
criteria = "safe-to-deploy"

[[exemptions.wayland-cursor]]
version = "0.29.5"
criteria = "safe-to-deploy"

[[exemptions.wayland-protocols]]
version = "0.29.5"
criteria = "safe-to-deploy"

[[exemptions.wayland-scanner]]
version = "0.29.5"
criteria = "safe-to-deploy"

[[exemptions.wayland-sys]]
version = "0.29.5"
criteria = "safe-to-deploy"

[[exemptions.wayland-sys]]
version = "0.30.1"
criteria = "safe-to-deploy"

[[exemptions.web-time]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.webbrowser]]
version = "0.8.10"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-wsapoll]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.winit]]
version = "0.28.6"
criteria = "safe-to-deploy"

[[exemptions.x11-dl]]
version = "2.21.0"
criteria = "safe-to-deploy"

[[exemptions.x11rb]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.x11rb-protocol]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.xcursor]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.xml-rs]]
version = "0.8.14"
criteria = "safe-to-deploy"

[[exemptions.zstd]]
version = "0.12.3+zstd.1.5.2"
criteria = "safe-to-deploy"

[[exemptions.zstd-safe]]
version = "6.0.5+zstd.1.5.4"
criteria = "safe-to-deploy"

[[exemptions.zstd-sys]]
version = "2.0.8+zstd.1.5.5"
criteria = "safe-to-deploy"
